name: ADA Workflow
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  accessibility:
    runs-on: ubuntu-latest
    env:
      PORT: 4000
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: Install Ruby Dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build Site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build
      - name: Start up jekyll server
        run: bundle exec jekyll serve &
      - name: Wait for server
        run: npm start &
      - name: Test Accessibility
        id: run-ada-tests
        run: sleep 50 & npm run accessibility 2>&1 | tee pa11y_output.txt
      - name: Read pa11y_output file.
        id: pa11y_output
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pa11y_output.txt
      - name: Check for pa11y failures.
        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
        run: |
          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
          exit 1
  deploy:
    needs: accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  report:
    needs: [deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"
