name: ADA Workflow
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  accessibility:
    runs-on: ubuntu-latest
    env:
      PORT: 4000
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: Install Ruby Dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build code
        run: |
          npm run build
      - name: Start up jekyll server
        run: bundle exec jekyll serve &
      - name: Test Accessibility
        id: run-ada-tests
        run: |
          sleep 30
          npm run accessibility
      - name: End ADA
        run: |
          echo "End ADA"
  deploy:
    needs: accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  report:
    needs: [deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"
